config/routes.rb
Paginacja::Application.routes.draw do
resources :users

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base

	paginates_per 3
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@q = User.search(params[:q])
	@users = @q.result(:distinct => true).order(:name).page params[:page]
  end

  def show
	@user = User.find(params[:id])
  end

  def new
	@user = User.new
  end

  def create
	@user = User.new(params[:user])
	if @user.save
		redirect_to user_path(@user)
	else
		render :action => "new"
	end
  end
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def
 index
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paginacja</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.haml
%h1 Uzytkownicy:
= search_form_for @q do |f|
 = f.label :name, "Imie:"
 = f.text_field :name_cont
 = f.label :surname, "nazwisko:"
 = f.text_field :surname_cont
 = f.submit
- for user in @users
 %p.meta
 #{user.name}
 #{user.surname}
 #{user.age}
 = link_to "Pokaz uzytkownika", user_path(user)
%br
%br
%br
= paginate @users
= link_to "Dodaj uzytkownika", new_user_path

app/views/users/new.html.haml
= form_for @user do |f|
  .clearfix
    = f.label :name, "Imię:"
    .input= f.text_field :name, :class => "xlarge"
  .clearfix
    = f.label :surname, "Nazwisko:"
    .input= f.text_field :surname
  .clearfix
    = f.label :age, "Wiek:"
    .input= f.text_field :age, :class => "xlarge"
  .clearfix.center
    = f.submit "Zapisz", :class => "btn primary"

%p
= link_to "Wróć do użytkowników", users_path

app/views/users/show.html.haml
.post
  %h2.title
    = link_to @user.name, user_path(@user)
    = @user.surname
    = @user.age
%br
= link_to "Dodaj nowego uzytkownika", new_user_path
%p
= link_to "Wroc do uzytkownikow", users_path

app/views/welcome/index.html.haml


%h1 Uzytkownicy

= link_to "Pokaż użytkowników", users_path